name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Executable
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --name=HSRCharEval main.py

      - name: Upload EXE to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/HSRCharEval.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
